version: '3.6'
services:
  "cloudlab":
    build: ""
    image: cloudlab:0.0.1-SNAPSHOT
    ports:
      - "8089:8089"
    volumes:
      - "./logs/cloudlab:/data/logs/cloudlab"
    env_file:
      - .env
    restart: always
    deploy:
      replicas: 1
      update_config:
        delay: 10s
        parallelism: 2
      restart_policy:
        condition: always

