AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Cloud Lab API written with spring-cloud-function web-proxy support

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  CloudLabFunction:
    Type: AWS::Serverless::Function
    Properties:
      #      AutoPublishAlias: bcn
      FunctionName: CloudLabFunction
      Handler: com.amazonaws.serverless.proxy.spring.SpringDelegatingLambdaContainerHandler::handleRequest
      Runtime: java21
      SnapStart:
        ApplyOn: PublishedVersions
      CodeUri: .
      MemorySize: 1024
      Policies:
        - AWSLambdaBasicExecutionRole
        - AmazonDynamoDBFullAccess
        - AmazonS3FullAccess
      Timeout: 30
      Environment:
        Variables:
          MAIN_CLASS: com.citi.cloudlab.CloudlabApplication
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'

Outputs:
  CloudLabApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/cloudlab'
    Export:
      Name: CloudLabApi


