server:
  port: ${SERVER_PORT:8089}
spring:
  application:
    name: cloudlab
  profiles:
    active: ${PROFILE:dev}
  webflux:
    base-path: /cloudlab
logging:
  file:
    path: ${LOG_PATH:/data/logs}